
services:
  # 1. Serviço de Backend (API)
  - type: web
    name: minha-api
    env: docker
    region: ohio
    plan: free
    rootDir: server # Define a pasta 'server' como a raiz do contexto do Docker
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: 3001

  # 2. Serviço de Frontend (Nginx)
  - type: web
    name: meu-frontend
    env: docker
    region: ohio
    plan: free
    rootDir: client # Define a pasta 'client' como a raiz do contexto do Docker
    dockerfilePath: Dockerfile
    envVars:
      - key: BACKEND_URL
        value: "https://RPG_With_Friends.onrender.com" # Substitua pelo nome do seu serviço de backend
